DROP all objects;

CREATE TABLE MPA (
	MPA_ID INTEGER AUTO_INCREMENT,
	MPA_NAME varchar(255),
	CONSTRAINT MPA_PK PRIMARY KEY (MPA_ID)
);

CREATE TABLE FILMS (
	FILM_ID INTEGER AUTO_INCREMENT,
	NAME varchar(255),
	DESCRIPTION varchar(255),
	RELEASE_DATE timestamp,
	duration integer,
	MPA_ID integer,
	CONSTRAINT FILM_PK PRIMARY KEY (FILM_ID),
	CONSTRAINT FILMS_FK FOREIGN KEY (MPA_ID) REFERENCES PUBLIC.MPA(MPA_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE USERS (
	USER_ID INTEGER AUTO_INCREMENT,
	NAME varchar(255),
	EMAIL varchar(255),
	LOGIN varchar(255),
	BIRTHDAY timestamp,
	CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE LIKES (
	FILM_ID INTEGER not null,
	USER_ID INTEGER not null,
	CONSTRAINT LIKES_FK FOREIGN KEY (FILM_ID) REFERENCES FILMS(FILM_ID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT LIKES_FK_1 FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE FRIENDS (
	USER_ID INTEGER,
	FRIEND_ID INTEGER,
	CONSTRAINT FRIENDS_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
	CONSTRAINT FRIENDS_FK_1 FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE GENRES (
	GENRE_ID INTEGER AUTO_INCREMENT,
	GENRE_NAME varchar(255),
	CONSTRAINT GENRES_PK PRIMARY KEY (GENRE_ID)
);

CREATE TABLE FILM_GENRES (
	FILM_ID INTEGER,
	GENRE_ID INTEGER,
	CONSTRAINT FILM_GENRES_FK FOREIGN KEY (FILM_ID) REFERENCES FILMS(FILM_ID),
	CONSTRAINT FILM_GENRES_FK_1 FOREIGN KEY (GENRE_ID) REFERENCES GENRES(GENRE_ID)
);